### ISSUE TITLE
Чувак, ты тут?

### ISSUE THREAD

**Issue by bertsol** [kinglamer/ArcomageHome#80]

**Comment by kinglamer** [comment]
Ага

**Comment by bertsol** [comment]
Прошу прощения, что сразу перешел на "ты"
У меня проблема с Вашим приложением, а на кону курсовая, для которой я его выбрал
Уже писал вашему товарищу, дабы он помог нас связать, мы можем пообщаться где нибудь в другом месте, или вам будет удобно и тут?
Просто дня 2 безвылазно я провел, пытаясь решить проблему, но я в отчаянии, а срок сдачи все ближе и ближе...
Понимаю Вам может быть не до такой мелочи, однако я в смятении и кажется только вы, как автор, сможете мне помочь

**Comment by kinglamer** [comment]
все нормально, можно на ты. 
напиши пожалуйста мне в контакте https://vk.com/chishir или опиши проблему здесь, попробую исправить
